-- CreateTable (全部按 income_25.4.1-6.29.csv 表头建字段)
CREATE TABLE "StoreOrderSettlement" (
    "id" TEXT NOT NULL,
    "statementDate" TEXT NOT NULL,
    "statementId" TEXT NOT NULL,
    "paymentId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "currency" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "orderAdjustmentId" TEXT NOT NULL,
    "skuId" TEXT,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    "productName" TEXT NOT NULL,
    "skuName" TEXT,
    "orderCreatedDate" TEXT,
    "orderShipmentDate" TEXT,
    "orderDeliveryDate" TEXT,
    "totalSettlementAmount" TEXT NOT NULL,
    "netSales" TEXT,
    "grossSales" TEXT,
    "grossSalesRefund" TEXT,
    "sellerDiscount" TEXT,
    "sellerDiscountRefund" TEXT,
    "shipping" TEXT,
    "tiktokShopShippingFee" TEXT,
    "fulfilledByTiktokShopShippingFee" TEXT,
    "signatureConfirmationServiceFee" TEXT,
    "shippingInsuranceFee" TEXT,
    "customerpaidShippingFee" TEXT,
    "customerpaidShippingFeeRefund" TEXT,
    "tiktokShopShippingIncentive" TEXT,
    "tiktokShopShippingIncentiveRefund" TEXT,
    "shippingFeeSubsidy" TEXT,
    "returnShippingFee" TEXT,
    "fbtFulfillmentFee" TEXT,
    "customerShippingFeeOffset" TEXT,
    "shippingFeeDiscount" TEXT,
    "returnShippingLabelFee" TEXT,
    "fbtFulfillmentFeeReimbursement" TEXT,
    "returnShippingFeePaidByCustomers" TEXT,
    "returnShippingFeeReimbursement" TEXT,
    "fees" TEXT,
    "transactionFee" TEXT,
    "referralFee" TEXT,
    "refundAdministrationFee" TEXT,
    "affiliateCommission" TEXT,
    "affiliatePartnerCommission" TEXT,
    "affiliateShopAdsCommission" TEXT,
    "tiktokShopPartnerCommission" TEXT,
    "cofundedPromotionSellerfunded" TEXT,
    "smartPromotionFeeTax" TEXT,
    "cofundedCreatorBonus" TEXT,
    "affiliateCommissionDeposit" TEXT,
    "affiliateCommissionRefund" TEXT,
    "affiliatePartnerShopAdsCommission" TEXT,
    "campaignServiceFee" TEXT,
    "campaignResourceFee" TEXT,
    "salesTaxOnReferralFees" TEXT,
    "smartPromotionFee" TEXT,
    "adjustmentAmount" TEXT,
    "adjustmentReason" TEXT,
    "relatedOrderId" TEXT,
    "col60" TEXT,
    "customerPayment" TEXT,
    "customerRefund" TEXT,
    "sellerCofundedVoucherDiscount" TEXT,
    "sellerCofundedVoucherDiscountRefund" TEXT,
    "platformDiscounts" TEXT,
    "platformDiscountsRefund" TEXT,
    "platformCofundedVoucherDiscounts" TEXT,
    "platformCofundedVoucherDiscountsRefund" TEXT,
    "adsReferralFeeDiscount" TEXT,
    "salesTaxPayment" TEXT,
    "salesTaxRefund" TEXT,
    "retailDeliveryFeePayment" TEXT,
    "retailDeliveryFeeRefund" TEXT,
    "customerpaidShippingFeeBeforeDiscounts" TEXT,
    "sellerShippingFeeDiscount" TEXT,
    "tiktokShopShippingFeeDiscountToCustomer" TEXT,
    "modeOfTiktokShopShippingFeeDiscountToCustomer" TEXT,
    "returnShippingFeePaidByCustomers2" TEXT,
    "estimatedChargeablePackageWeight" TEXT,
    "chargeablePackageWeight" TEXT,
    "fbtChargeableGoodsWeight" TEXT,
    "collectionMethods" TEXT,
    "deliveryOption" TEXT,
    "signatureConfirmationServiceFeeType" TEXT,
    "col85" TEXT,
    "col86" TEXT,
    "col87" TEXT,
    "col88" TEXT,
    "col89" TEXT,
    "col90" TEXT,
    "col91" TEXT,
    "col92" TEXT,
    "col93" TEXT,
    "col94" TEXT,
    "col95" TEXT,
    "col96" TEXT,
    "col97" TEXT,
    "col98" TEXT,
    "col99" TEXT,
    "col100" TEXT,
    "col101" TEXT,
    "col102" TEXT,
    "col103" TEXT,
    "col104" TEXT,
    "col105" TEXT,
    "col106" TEXT,
    "col107" TEXT,
    "col108" TEXT,
    "col109" TEXT,
    "col110" TEXT,
    "col111" TEXT,
    "col112" TEXT,
    "col113" TEXT,
    "col114" TEXT,
    "col115" TEXT,
    "col116" TEXT,
    "col117" TEXT,
    "col118" TEXT,
    "col119" TEXT,
    "col120" TEXT,
    "col121" TEXT,
    "col122" TEXT,
    "col123" TEXT,
    "col124" TEXT,
    "col125" TEXT,
    "col126" TEXT,
    "col127" TEXT,
    "col128" TEXT,
    "col129" TEXT,
    "col130" TEXT,
    "col131" TEXT,
    "col132" TEXT,
    "col133" TEXT,
    "col134" TEXT,
    "col135" TEXT,
    "col136" TEXT,
    "col137" TEXT,
    "col138" TEXT,
    "col139" TEXT,
    "col140" TEXT,
    "col141" TEXT,
    "col142" TEXT,
    "col143" TEXT,
    "col144" TEXT,
    "col145" TEXT,
    "col146" TEXT,
    "col147" TEXT,
    "col148" TEXT,
    "col149" TEXT,
    "col150" TEXT,
    "col151" TEXT,
    "col152" TEXT,
    "col153" TEXT,
    "col154" TEXT,
    "col155" TEXT,
    "col156" TEXT,
    "col157" TEXT,
    "col158" TEXT,
    "col159" TEXT,
    "col160" TEXT,
    "col161" TEXT,
    "col162" TEXT,
    "col163" TEXT,
    "col164" TEXT,
    "col165" TEXT,
    "col166" TEXT,
    "col167" TEXT,
    "col168" TEXT,
    "col169" TEXT,
    "col170" TEXT,
    "col171" TEXT,
    "sourceFileName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StoreOrderSettlement_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "StoreOrderSettlement_statementDate_idx" ON "StoreOrderSettlement"("statementDate");
CREATE INDEX "StoreOrderSettlement_orderAdjustmentId_idx" ON "StoreOrderSettlement"("orderAdjustmentId");
CREATE INDEX "StoreOrderSettlement_paymentId_idx" ON "StoreOrderSettlement"("paymentId");
CREATE INDEX "StoreOrderSettlement_createdAt_idx" ON "StoreOrderSettlement"("createdAt");
